### ISSUE TITLE
Needs some notes about 10.11 and System Integrity Protection

### ISSUE THREAD

**Issue by laserpilot** [laserpilot/Installation_Up_4evr#7]
http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

**Comment by laserpilot** [comment]
Not quite sure what parts of the guide this limits yet, I need to revisit a couple of the lower level/sudo ones that are in there and see if they still work - if anyone catches something off in 10.11, please let me know

**Comment by wjrro** [comment]
I think this issue can be closed with the last pull request?
