### ISSUE TITLE
Best version of OSX?

### ISSUE THREAD

**Issue by prismspecs** [laserpilot/Installation_Up_4evr#8]
I know this is a rather open ended question but I'm curious if in your experience it's best to downgrade to a particular OS. Sierra is scaring me (not even an option anymore to open apps from untrusted devs???) so maybe 10.8?

**Comment by laserpilot** [comment]
I've been running an installation for a year and a half on 10.10.4 (I think 4 - as of July 2015) and it has been great. No client issues except projectors blowing bulbs.

**Comment by prismspecs** [comment]
Would you mind if I emailed you and asked a few quick questions? I don't want to get you on the hook or anything, but maybe you can give me general advice so I can dig into research? It might be that I've already thought of everything...

**Comment by laserpilot** [comment]
Sure. I don't want to keep my email public here but there is a form on my website that works. Let me know if you can't find it
